FROM ubuntu

RUN apt update && apt-get install -y \
    curl \
    wget \
    git \
    vim \
    nano \
    && rm -rf /var/lib/apt/lists/*

# download java using ADD
ADD https://download.oracle.com/java/24/latest/jdk-24_linux-x64_bin.deb /tmp/jdk-24_linux-x64_bin.deb

RUN apt install -y /tmp/jdk-24_linux-x64_bin.deb \
    && rm /tmp/jdk-24_linux-x64_bin.deb

WORKDIR /tinum/welcome
